### ISSUE TITLE
Add protein sequences to prepped design units

### ISSUE THREAD

**Issue by kaminow** [choderalab/asapdiscovery#106]
This can be accomplished with the `OEStructureMetadata` and `OESequenceMetadata` classes. We can also take this opportunity to start doing some stuff dynamically. For example, automatically detecting which chains contain the protomers instead of assuming the A and B chains, and potentially performing a sequence alignment to make sure that the sequence only represents the part of the protein that's actually present in the structure.

**Comment by apayne97** [comment]
This was done in #116 ! although dynamic recognition and sequence alignment and stuff hasn't happened yet
