### ISSUE TITLE
Standardize script / repo organization

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#132]
# Description
So we have these potential elements
1. python api in modules
2. jupyter notebooks for testing and exploring various things
3. python scripts that import from the api
4. cluster-submission scripts that run the python scripts with specific inputs, potentially useful as examples
5. tests
6. repo / packaging elements (i.e. environment yamls)

I'm not sure exactly where everything should be put but I think we should stick to a specific format once we decide on it. I had been thinking it would be best to split everything up among the modules but it might be better to have an examples script and put the cluster scripts / explanatory jupyter notebooks and README's there.

## Suggested organization
- asapdiscovery
     - docking
          - __init__.py
          - docking.py
          - analysis.py
          ...
          - scripts (maybe rename to cli)
          - tests
     - simulation
     ...
- examples
     - fauxalysis-generation-from-pdbs
          - README.md
          - cluster_script.sh
          - jupyter_notebook.ipynb [either in place of the cluster script or in addition to in order to demonstrate how to use the api]
          - log_files
               - cluster_script.out
               - cluster_script.stderr
- devtools
     - cond-envs
     - troubleshooting-notebooks (jupyter notebooks)

## Potentially related to these issues / pull requests
- [x] #98
- [x] #53 
- [x] #51 
- [x] #49 
- [x] #48 
- [ ] #20 
- [x] #4

**Comment by dotsdl** [comment]
For our approach to CLIs, I'm working to establish a general pattern in `asapdiscovery-data`: https://github.com/choderalab/asapdiscovery/blob/aws-s3-upload/asapdiscovery-data/asapdiscovery/data/cli.py

Basically, each namespace package gets its own CLI, such as `asapdiscovery-data`. This CLI can then have its own tree of subcommands. In the case of `asapdiscovery-data`, we have:
- `asapdiscovery-data postera` : interaction points for PostEra
- `asapdiscovery-data aws s3` : interaction points for AWS S3
- and so on

There may still be a place for standalone scripts within a given namespace package, but I think we should try to push toward CLI points where possible instead.

**Comment by apayne97** [comment]
I think we've made great progress on this!
