### ISSUE TITLE
Move protein prep to its own module?

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#134]
I think it makes sense to make a separate "modeling" module. In other words, "protein prep" could be its own category, with outputs to simulation, docking, and datavisualization separately. Just a thought.

**Comment by JenkeScheen** [comment]
"Modelling" might be too vague - perhaps something more specific like "structural_modelling"?

**Comment by apayne97** [comment]
i would love to have the module name not include an underscore?

**Comment by kaminow** [comment]
I think just `modeling` is probably ok since it'll be `asapdiscovery.modeling`, which kind of implies the context

**Comment by JenkeScheen** [comment]
Agreed with keeping underscores out of this. let's go with `asapdiscovery.modeling`

**Comment by apayne97** [comment]
ok, let's do that!
