### ISSUE TITLE
Making tests scripts in modeling work as part of our CI

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/asapdiscovery#182]
Tests scripts in modeling need to be executed as part of our CI workflows. This requires 
- [x] #186
- [x] #187

**Comment by apayne97** [comment]
https://github.com/choderalab/asapdiscovery/pull/104/files#r1134714922

**Comment by apayne97** [comment]
I strongly suggest we need to do both of these things in order to have functioning tests / examples!

**Comment by apayne97** [comment]
finished with #225
