### ISSUE TITLE
Improve check_completed function

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#185]
Maybe this doesn't make sense to have as a part of the api, because this is a bit script specific, but currently we have several near-duplicate versions of a `check_completed function` that does some weird exception catching. This should be updated and improved in all of its uses.

https://github.com/choderalab/asapdiscovery/pull/104/files#r1147964482

**Comment by apayne97** [comment]
https://github.com/choderalab/asapdiscovery/pull/104#discussion_r1147972402

**Comment by hmacdope** [comment]
I think we have mostly replaced this with loading to/from JSON
