### ISSUE TITLE
Clean up code for `e3nn` and `schnet` in `ml` utilities?

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#188]
We have a fair bit of stuff left over in `ml.util` from the schnet and e3nn models. As far as I know (@kaminow) these models have been removed (will they come back?). No rush but long term if these are not going to return we should clean up branching in the utility code.

**Comment by kaminow** [comment]
We're still going to be using the `SchNet` and `e3nn` models, just not the ones that were previously in the package (`SchNetBind` and `E3NNBind`) as they've been superseded by the models in `mtenn`.

**Comment by hmacdope** [comment]
Thanks for clarifying. :)
