### ISSUE TITLE
Re-direct print statements to log file

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#194]
There are some functions we've written that come with their own print statements ("Loading XXX file!", etc), and I think it would be nice to redirect some of those outputs to individual logger files in a clean way (i.e. without having to re-write all of our functions to take a logging object as a parameter).

I just learned that if you don't specify a log file it will just print to stdout so maybe we can have a PR that just replaces every instance of print with logger.info (or warning, error, etc).

Then anytime we run a function, if no log file is specified, it will retain its previous behaviour (printing to stdout), and if we do specify one, then it will print to a log file. not sure how this interacts with @hmacdope logging.FileLogger class.

i.e. in #192 I've improved run_docking_oe.py to use a logger. but the `run_docking_oe` function (imported from asapdiscovery.docking.docking) that is called inside `mp_func` has its own print statements which are not captured.

**Comment by hmacdope** [comment]
Generally using `logger.info` is better than using  `specificlogger.info()` so I would support this.

**Comment by apayne97** [comment]
I tried to implement some of these changes in #192 but I can't get it to behave correctly.

**Comment by hmacdope** [comment]
What exactly is going wrong?

**Comment by apayne97** [comment]
So you can only change the root logger configuration 1 time, which means you have to specify a name and then use getLogger if you want different functions to all write to the same log file. I think the implementation I've made now seems to be working well.

**Comment by hmacdope** [comment]
If your happy with a modified implementation lets roll with that. I can review as well on the PR.

**Comment by apayne97** [comment]
Added you as a reviewer!

**Comment by hmacdope** [comment]
Ta! Reviewing now.
