### ISSUE TITLE
Update pebble implementation in run_docking_oe to match other protocols

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#224]
# Description
The PR that added pebble timeout management of run_docking_oe (#218) did something things that will conflict with some updates I've made in #213 and #192.

# Things to Address
- [x] i think we should use logger instead of print statements
- [x] we need to decide whether we want to depend on all the results being returned to a single node or just concatenate the results later. I would probably vote for the latter (?)
- I decided to keep this, as it doesn't seem to be even close to being the main bottleneck, as long as jobs are submitted as a job array it doesn't really seem to affect the memory cost
- [x] there is no `else` for `if args.num_cores > 1:`, which means that if num_cores is 1 nothing will happen? is this the desired behaviour?

**Comment by kaminow** [comment]
1. sounds good, I can open a PR for this, or feel free to just make the changes in #213 
2. is this something you've implemented somewhere, or just an idea that you had? I'm fine with either option (and happy to implement/help implement), I just don't see it anywhere
3. the `else` for the `args.num_cores` check is on L534:
https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py#L534

**Comment by apayne97** [comment]
> sounds good, I can open a PR for this, or feel free to just make the changes in https://github.com/choderalab/asapdiscovery/pull/213
I'll proceed with making the changes there!

> is this something you've implemented somewhere, or just an idea that you had? I'm fine with either option (and happy to implement/help implement), I just don't see it anywhere
Removing the results-returning I have implemented in this branch, and have at least once before implemented a script to concatenated results afterwards.

The only thing is, I'm not sure how to use this pebble implementation as it depends on the results getting returned within this script?

> the else for the args.num_cores check is on L534:
https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py#L534
My bad, I think I had accidentally deleted it while resolving merge conflicts. Thanks!

**Comment by kaminow** [comment]
> The only thing is, I'm not sure how to use this pebble implementation as it depends on the results getting returned within this script?

I don't think I changed anything in `mp_func` with the pebble stuff. it definitely still dumps the pickle files, so we can get rid of the return statement if we want. the only reason to return and go through the results is to check which runs timed/errored out. if we don't care about that, then you can go ahead with getting rid of the results-returning

**Comment by apayne97** [comment]
Resolved in #226
