### ISSUE TITLE
Best way to standardize cluster scripts?

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#230]
I really appreciate being able to save examples of how to actually run the python scripts we've made within the repo.
however, as @JenkeScheen has pointed out, any specific cluster script needs to be changed for user environments, etc.

Is there a smart way to do this?

I know for specific cases it can make sense to generate another level of abstraction, where a script takes a bash script template, edits it, and saves the result to the output directory. But this seems like a bit of overkill to include with all the scripts we might want to run.

**Comment by apayne97** [comment]
but at least for some kinds of job scheduling things (i.e. the specifics of using job arrays), I feel like it would be nice to keep that information somewhere? 

I guess there's a conflict here between generalizability and reusability when function as a python package, and reproducibility when functioning as a computational lab notebook. I would like to use it as a repository for keeping track of the specific things I did, but maybe since this isn't my own repo that isn't really what this is for? *sigh*

**Comment by hmacdope** [comment]
Closing as stale
