### ISSUE TITLE
create end-to-end single-reference prep+dock workflow

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#234]
Suppose we have 1 non-fragalysis reference crystal with bound ligand, and a bunch of ligands in 2D SDF/SMILES. Currently docking them to that reference is a bit complex because it requires making a very specific folder structure, a CSV with specific column names, then prepping the structure, then docking the ligands (see https://www.notion.so/asapdiscovery/c4fe298017fb4739a36b50ff6b6fddc8?v=f1c7224d73c345079803906bf56f3bf1&p=ef8de84fbb014c8a890a620b1341fa9c&pm=s). For fragalysis-based docking it's been a good idea to keep prepping+docking separate steps, but now that ASAP will be branching out to newer targets we'll want to be able to prep+dock more flexibly to newer targets whenever this is queried by medchemists.

We should come up with a way to make this a 1-step process (possible with a quick CLI) that will take care of the prepping + docking. This might require some tinkering with `prep_proteins.py` to make it a bit more standalone (i.e. less dependent on a specific folder structure, but instead just able to ingest a single PDB file). 

The script would ingest the protein complex PDB and the (multi)ligand SDF/SMILES. Steps in the process would be:
1) prep the protein given some information (seqres, loop_db path)
2) run MCS on all input ligands to match the ligand in the PDB
3) dock all ligands

Alternatively, if there is no reference ligand in the PDB, then ligands should be docked blindly as is already possible in `run_docking_oe.py`. 

Thoughts?

**Comment by hmacdope** [comment]
Yes @JenkeScheen! Very important step I think both in terms of modularising the existing setup and for project support, happy to take this one on.

**Comment by JenkeScheen** [comment]
@hmacdope can we prioritise this ticket? I've been debugging all morning to try and get a docking run off the ground with some non-fragalysis structures. This functionality should be a core concept in the codebase, imo.

**Comment by hmacdope** [comment]
yep absolutely, sorry for the delay.
