### ISSUE TITLE
Split out input generation into its own function / scripts

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#242]
One of the ways I think we can improve pipelining (and readability) in the codebase is to split out the generation of the exact input files / metadata into its own step for i.e. docking and protein prep. Kinda making steps towards this in #241 and #238.

This way the functions that are already hard enough to read bc of all the options they have (docking, protein prep) can be focused on those tasks, and always expect the same input.

This also has the benefit of being able to subset a dataset using a separate function, or script, or many different types of scripts, etc.

**Comment by hmacdope** [comment]
This is outdated now AFAIK, @apayne97 can reopen if not.
