### ISSUE TITLE
Should we be using the data on postera website?

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/asapdiscovery#256]
As shown in the ASAP meeting we should have access to the Postera data (even programmatic access through an API), we already have code that  can help with that in the repo (the postera code in `asapdiscovery-data`). I just thought I raised the question here for folks, since it seems relevant that we might find using this data useful for our purposes and it seems we could do it in an automated way.

**Comment by hmacdope** [comment]
Outdated now.
