### ISSUE TITLE
Investigate why DGL 1.1 breaks our weight comparisons for constructing GAT model

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#260]
Investigate why DGL 1.1 breaks our weight comparisons for constructing GAT model

**Comment by kaminow** [comment]
it seems like this issue is caused by [this commit](https://github.com/dmlc/dgl/commit/29e666152390c272e0115ce8455da1adb5fcacb1). I'll need to rework how the GAT model is built based on their new `bias` assignment in the `GATConv` class
