### ISSUE TITLE
Add test for prep with  loop database

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#269]
From slack: @apayne97 

I'd like to have a protein prep test that includes passing the loop database...should we include the loopdb in the AWS S3 bucket? the full one is 13 Gb but I think John might have already created a shorter one with just the MPRO structures 

@jchodera : SpruceTK loop database builder docs:
https://docs.eyesopen.com/applications/spruce/loopdb_builder/loopdb_builder_example.html

You just need to download the OpenEye Applications
https://www.eyesopen.com/customer-software-download

Find the loopdb_builder and run
```
./loopdb_builder -in /path/to/fragalysis/pdb/files/ -source_name fragalysis -prefix fragalysis-mpro
```

You can download the fragalysis database, download the OpenEye Applications for Linux, and then use loopdb_builder to build a tiny loop database from the fragalysis database to use in prep. Or even just run it on a single structure

**Comment by apayne97** [comment]
Done in #272
