### ISSUE TITLE
Schema Ideas for Protein Prep and Beyond

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#273]
* replace the `Dataset.iterator` behaviour so that Dataset is iterable, indexible, etc natively.
* Fields to add to CrystalCompoundData (or perhaps a Target object that is contained within the CrystalCompoundData)
    * other useful ids
    * sequence
* make it possible to load all the target-specific information about prepping from a yaml file or via programatic generation (i.e. the MoleculeFilter, active site chain, and active site fields)

**Comment by apayne97** [comment]
In the future the protein sequence should just be included within the schema and then anything that needs to i.e. make mutations or add the SEQRES will use that sequence

**Comment by apayne97** [comment]
## Design Ideal
### High level:
1. A series of parameters gets passed to `prepare-protein-csv` that generates CrystalCompoundData objects and serializes them to a CSV
2. This CSV is read, converted to a set of CrystalCompoundData objects, and these are prepared using a series of options.

### Parameters for each CrystalCompoundData object:
This should include anything that might be different for each model.
- [ ] output_name
- [ ] compound_id
- [ ] dataset name from Fragalysis
- [ ] smiles string of ligand
- [ ] file path of of PDB structure to prep
- [ ] file path of sdf file
- [ ] active site chain (chain containing the active site)
- [ ] ligand chain (chain containing the ligand --> annoyingly, this can be different from the active site)
- [ ] active_site : the OpenEye formatted string identifying where the binding site is (necessary for preparing protein-only design units)

### Prepping Tasks
|Task|Currently Handled By|Moved To|
|-|-|-|
|alignment|align_receptor or superpose_mol|align_target|
|remove undesired molecules|remove_extra_ligands or split_initial_complex or align_receptor|???|
|add seqres|mutate_residues||
|fix incorrect residues|spruce_protein||
|build loops|spruce_protein|

### Parameters for the protein prep functionitself:
- [ ] the serialized CrystalCompoundDataset (a csv file)
- [ ] the reference to align to
- [ ] the chain of the reference to align to
- [ ] seqres
- [ ] loop_db
- [ ] whether or not to keep just the protein (and potentially water)
- [ ] whether or not to keep waters

**Comment by apayne97** [comment]
it would be nice to give the Dataset class a "len" output

**Comment by hmacdope** [comment]
Outdated now that schema have moved onto second gen? @apayne97 re-open if not.
