### ISSUE TITLE
Move scientific / exploratory code to new repo

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#279]
Related to #249 

This will probably be a PR that looks like a bunch of deleted files.

I think my heuristic for choosing what to remove will look like: if it only runs in a specific places with a specific set of input files not specified in the test suite, then it should get moved to a scientific repo.

A question I have for doing that is how to pin different parts of that repo to different states of this repo?

**Comment by hmacdope** [comment]
@apayne97 did you get what was needed out of this? You can always pin to a state of this repo by using a specific git sha, but shouldn't be nessecary IMO.

**Comment by apayne97** [comment]
Yeah, I moved what I needed to 
https://github.com/choderalab/asapdiscovery-mers-docking
https://github.com/choderalab/asapdiscovery-sars-retrospective
