### ISSUE TITLE
Add code to run_docking_oe to be able to run self-docking

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#284]
Given a set of receptors, pull out the ligands from those receptors and redock using HYBRID. The goal is just to relax the pose of ligands transfered to new structures using their original pose.

Currently implemented poorly in:
https://github.com/choderalab/asapdiscovery-mers-docking

I would like to re-implement this in this repo once some of the major schema changes have been made

**Comment by hmacdope** [comment]
Outdated as now self-docking is run with new API
