### ISSUE TITLE
Composable steps to run a simulation

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#292]
I think I would rather have composable steps to run a simulation rather than having a single Simulator object, but we can discuss in our dev meeting! Makes sense to me so far!

_Originally posted by @apayne97 in https://github.com/choderalab/asapdiscovery/pull/246#discussion_r1216109564_

**Comment by hmacdope** [comment]
@apayne97 does this still apply?

**Comment by apayne97** [comment]
No, I think what we've done is fine
