### ISSUE TITLE
Add progress bar to simulation GIFs.

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#293]
From @jchodera  on slack: Can you put a progress bar or a timer in the corner of these movies? If this is meant to be a “something happens during this movie” movie, rather than just a “fluctuating at equilibrium” movie, it’s very difficult to see where the movie starts and where you are within it because it’s an animated gif

**Comment by JenkeScheen** [comment]
Thanks Hugo. I think I know a way to do this, will play around with this today. Would we implement this in https://github.com/choderalab/asapdiscovery/pull/246 or a subsequent PR?

**Comment by JenkeScheen** [comment]
Here's a prototype, I tested this locally on a folder with PNGs. This should be ~ ready to be injected into the workflow, might need some troubleshooting when it's switched to the `tmp` folder setup:
``` python
def addProgressBar(png_paths):
    """
    TODO: still needs logging, real-world testing.

    Adds a progress bar and nanosecond counter onto PNG images. This assumes PNG
    files are named with index in the form path/frame<INDEX>.png. Overlaying of these objects
    happens in-place.

    png_paths: list
        list of path strings to .png files
    """

    # global settings:
    frames_per_ns = 200 # this is default with how .xtc is written by OpenMM. 
    total_frames = len(png_files)

    for filename in png_files:
        # get this file's frame number from the filename and calculate total amount of ns simulated for this frame
        frame_num = int(filename.split("frame")[1].split(".png")[0])
        total_ns_this_frame = "{:.1f}".format(frame_num / frames_per_ns)

        # load the image.
        img = Image.open(filename)
        draw = ImageDraw.Draw(img, "RGBA")

        # get its dimensions (need these for coords); calculate progress bar width at this frame.
        width, height = img.size
        bar_width = frame_num / total_frames * width
        
        # draw the progress bar for this frame (black, fully opaque).
        draw.rectangle(((0, height-20), (bar_width, height)), fill=(0, 0, 0, 500))

        # draw the text that shows 
        draw.text((width-110, height-10), f"{total_ns_this_frame} ns", 
          # need to load a local font. For some odd reason this is the only way to write text with PIL.
          font=ImageFont.truetype('OpenSans-Regular.ttf', 65), 
          fill =(0, 0, 0), # make all black.
          anchor="md") # align to RHS; this way if value increases it will grow into frame.
        
        # save the image. 
        img.save(filename)
```
A practical way to inject this (probably somewhere around [here](https://github.com/choderalab/asapdiscovery/pull/246/files#diff-b1920fba8cab2a572f29ebacf98ea2d1a3a4a09367f09942ae8629ad1f96e5caR298-R301)) would be to just do:
``` python
with iio.get_writer(gif_filename, mode='I') as writer:  
    # add a progress bar to the .png files in-place.
    addProgressBar(png_paths)

    # then do the regular GIF generation steps.
    for filename in png_files:
        # now read in the PNG, then add to the GIF.
        image = iio.imread(filename)
        writer.append_data(image)
```
This results in GIFs that look like this:
![traj](https://github.com/choderalab/asapdiscovery/assets/43140137/e5de91a7-ad93-4592-963f-b90fbe7b7092)

---
@hmacdope did you want to make this a separate PR after https://github.com/choderalab/asapdiscovery/pull/246 is merged or just insert it there?

**Comment by hmacdope** [comment]
I ended up putting it in if thats ok?

**Comment by JenkeScheen** [comment]
we'll still need to increase precision from 1 to 3 points as per @jchodera's comment.
