### ISSUE TITLE
Fragalysis download issues and tests failing. 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#309]
```TestFragalysisDownload::test_sdfs_pdbs_fragalysis_download - zipfile.BadZipFile: Bad magic number for file header```

According to @apayne97 and @kamin the issue appears to be with the `smiles.smi` file that comes with the download. 

if the  "smiles_info" key is set to False everything works fine.

**Comment by apayne97** [comment]
I don't think this needs to be a Milestone issue - currently it seems to be working but we have no idea yet how to track the issue

**Comment by hmacdope** [comment]
Perhaps we can use a retry and a timeout. @ijpulidos pointed out that this is an important indicator of whether the data is actually downloadable.

**Comment by hmacdope** [comment]
This seems to have settled down, and regardless I think the tests are currently XFAILED.
