### ISSUE TITLE
Pull Compound_ID from a SMILES file for docking

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#323]
in `run_docking_oe.py` we just use numbers as the Compound_ID when we don't know what the ID should be.
in #246 the `dock_small_scale_end_to_end.py` uses the SMILES as the default name. 

Since the usual use case is to pull from a SMILES file, we should pull the Compound_ID as the second column in a smiles file.

**Comment by hmacdope** [comment]
Stale.
