### ISSUE TITLE
Very filenames and  long titles in SDFs can cause issues that jam up workflow components

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#329]
Beware very long (> 80 char) file names  and titles in SDFs, these can cause issues with components including RDKit and openeye parsing including segfaults.

**Comment by hmacdope** [comment]
This is fixed by a function that truncates file name lengths `aspadiscovery.data.utils.check_name_length_and_truncate` in #246

**Comment by JenkeScheen** [comment]
this highlights the need for us to start using some form of UUID for compounds. At least for the FECs workflow we're still using InChi for compound names, these can exceed >80 chars and are thus truncated, but this risks creating duped names between compounds.

We should probably start using the low-level compound identifier that the postera API uses (it's a random string so should be fine to use)

**Comment by hmacdope** [comment]
Reopening as a discussion point.

**Comment by hmacdope** [comment]
We do this now
