### ISSUE TITLE
Changing names of of experiments in CDD vault 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#346]
The names of the experiments in the CDD vault/Manifold  are being changed to new standardised names, we should support the new names in our CDD download process.

**Comment by kaminow** [comment]
currently the default assay name is the Moonshot SARS-2 protease dose response one, but both `download_moonshot_data.py`, and `filter_molecules_dataframe` and `parse_fluorescence_data_cdd` in `asapdiscovery.data.utils` have an option to specify a different name

**Comment by kaminow** [comment]
it might make sense though to add a dict somewhere mapping target to assay name, similar to the search URLs that we have

**Comment by hmacdope** [comment]
This is not well scoped and nothing on our end. Closing.
