### ISSUE TITLE
Investigate making a DU from a prepped protein target

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#347]
Speed up protein prep and saving by enabling quick creation of DesignUnits from a pre-prepped target.

@kaminow is not sure if this is possible but it feels like it should be.

If making a DesignUnit from a pre-prepped target is quick, then this is useful.

- [ ] What's the crossover point at which this is worth it? How fast does it have to be?

**Comment by kaminow** [comment]
Based on our meeting today, it seems like this is not something we want to do?

**Comment by apayne97** [comment]
Agreed, I think the alternatives for this will be discussed in #355 and #339
