### ISSUE TITLE
Regex capture from Fauxalysis is difficult

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#365]
Custom regex is needed to capture fauxalysis du names, which is can be a bit annoying.

**Comment by hmacdope** [comment]
On further investigation the whole fauxalysis csv based pipeline is a bit messed up.

**Comment by kaminow** [comment]
@hmacdope is this something we should talk about/that I can help with?

**Comment by hmacdope** [comment]
Yes let's discuss :)

**Comment by hmacdope** [comment]
Redundant wrt new workflows.
