### ISSUE TITLE
FEC workflow SEQRES should be configurable, for different targets

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#372]
SEQRES should be configurable, for different targets, currently always dumps the SARS-CoV-2 Mpro SEQRES in there. 

_Originally posted by @hmacdope in https://github.com/choderalab/asapdiscovery/pull/369#discussion_r1261879908_

**Comment by ijpulidos** [comment]
We should have yaml files with the SEQRES information, we probably should be extracting the sequences from them instead of hard coding it in the scripts/functions/methods.

**Comment by hmacdope** [comment]
Outdated now due to use of `alchemy` closing.
