### ISSUE TITLE
FragalysisFactory for generation of prep input Target and Ligand Schema from Fragalysis

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#383]
FragalysisFactory for generation of prep input Target and Ligand Schema from a fragalysis file system
This will looks something like the below in use.
```python
from asapdiscovery.data.schema_v2 import *

targets: List[Target], ligs: List[Ligand] = FragalysisFactory(fragalysis_path) 
```
OR we can also combine these into a combined schema, which may be neater.

```python
from asapdiscovery.data.schema_v2 import *

complexs: List[Complex] = FragalysisFactory(fragalysis_path)

**Comment by hmacdope** [comment]
@kaminow would this be of interest to you / would you have bandwidth?

**Comment by kaminow** [comment]
yeah definitely! I’m at ICML this week though and won’t be super productive, so if this is going to block other stuff then it might be better for someone else to take it
