### ISSUE TITLE
Split devtool conda env yamls into CI and production env components.

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#385]
The issue is that because there is no cudatoolkit on MacOS, you need to not have that explicitly listed as a dependency and instead let the solver pull in what it needs.

I think this highlights an issue, is the env yaml for CI or for someone to create an env for production? We really shouldn't be doing both with the same yaml IMHO for this reason

_Originally posted by @mikemhenry in https://github.com/choderalab/asapdiscovery/issues/384#issuecomment-1648710719_

**Comment by mikemhenry** [comment]
And I vote we just get this on conda-forge, then the answer is "install from conda-forge" https://github.com/choderalab/asapdiscovery/issues/20

**Comment by hmacdope** [comment]
Its waiting on a certain `dgl` package on CF.

**Comment by mikemhenry** [comment]
:upside_down_face:

**Comment by hmacdope** [comment]
This is fixed now
