### ISSUE TITLE
Consider pydantic settings managment 

### ISSUE THREAD

**Issue by jthorton** [choderalab/asapdiscovery#388]
We could consider making a pydantic settings class to cover all of the settings [here](https://github.com/choderalab/asapdiscovery/blob/a4bda414a8920ca161e303399e2ae4ce3026db82/asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py#L390-L422) as I am sure other work flows may need to reuse these like uploading the results of FEC? Pydantic can handle gathering the settings from the environment automatically see [here](https://docs.pydantic.dev/2.0/usage/pydantic_settings/#settings-management). We can then add validation methods which checks they are all set.

**Comment by hmacdope** [comment]
Second this, this is a great idea.
