### ISSUE TITLE
Show 2D ligand interaction network on docked poses 

### ISSUE THREAD

**Issue by jthorton** [choderalab/asapdiscovery#389]
I am not sure how useful this would be but it should be fairly easy to add an [interactive 2D ligand interaction ](https://prolif.readthedocs.io/en/latest/notebooks/visualisation.html#Ligand-Interaction-Network-(LigPlot))network of the generated pose, either docked or generated using FEGrow which could also be uploaded to postera?

**Comment by hmacdope** [comment]
Yes I think @JenkeScheen  investigated this but had some issues, skeleton issue #341 but happy to move discussion here. 
He and I would be welcome if you can get it to work!

**Comment by JenkeScheen** [comment]
Thanks @jthorton, I'll update https://github.com/choderalab/asapdiscovery/issues/341
