### ISSUE TITLE
Major refactor to better fit the format of a Python package

### ISSUE THREAD

**Issue by kaminow** [choderalab/asapdiscovery#4]
Arrange classes and functions into submodules to match other ML platforms, and add entry points for other programs and CLI usage. Addressing the following:

> * We might want to move the models into a `models/` subpackage, where we can call the files (modules) `schnet` and `e3nn` so you can `from .models.e3nn import E3NNBind` and `from .models.schnet import SchNetBind`. These are just stylistic choices, but will make things cleaner.
> * The training scripts should become [entry points](https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts). These allow you to organize the scripts that do things instead into (1) a Python API you can use from another program, (2) a method you can call with command-line arguments, and (3) an entry point defined in `setup.py` that builds an executable script on the path that calls (2) with the command-line arguments when you run it.
_Originally posted by @jchodera in https://github.com/choderalab/covid-moonshot-ml/pull/2#pullrequestreview-951031979_

**Comment by apayne97** [comment]
@kaminow is this done for now?

**Comment by kaminow** [comment]
I still need to do the second point above, but maybe we can close this for now and that can be opened as a new issue once we've split off the ML stuff into its own repo. @ijpulidos @mikemhenry thoughts?

**Comment by ijpulidos** [comment]
I think this was already addressed by the changes in #98. Closing.
