### ISSUE TITLE
Breaking change to `mtenn` to use internal units in upcoming 3.0 will invalidate old SchNet models 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#435]
Breaking change to `mtenn` to use internal units in upcoming 3.0 will invalidate old SchNet models

See: https://github.com/choderalab/mtenn/pull/25 

We should replace the ones we currently have. 

@kaminow to check that GAT models are unaffected.

**Comment by kaminow** [comment]
GAT models are indeed unaffected. I've merged choderalab/mtenn#25, but I pinned the `mtenn` version to 0.2.1 in the `asapdiscovery` conda env, so we shouldn't run into any problems. I'll bump the version and update the SchNet weights once they're ready, but we shouldn't have to change much code thanks to your work in #428
