### ISSUE TITLE
Keep a record of generated datasets with metadata

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#45]
As discussed in our previous comp-chem meetings, this will be important especially if we are ever automatically uploading to a database. We will want to keep track of some metadata so we can see which "experiment" various sets of docking results come from.

My proposal is to keep a csv somewhere, perhaps in the recently created `data/` directory, that has these columns:
## Columns
* `ID`: probably just a number?
* `Path_Data`: lilac relative path to dataset
* `Path_CSV`: lilac relative path to csv results file
* `Type`: (see type options below)
* `Status`: (see status options below)
* `Notes`: this is actually maybe the most important column, detailing what was done to produce this dataset and why it is different than the others
* `Source`: not sure how to standardize this but it would be good to have a version controlled link to the source files used to generate this dataset. Could be as simple as writing out the `datetime` the dataset was generated and the input files used (i.e. what arguments were passed to `hallucinate_fragalysis.py`)

## Type Options:
* `Docking`: just the raw docking result, unfiltered
* `Fauxalysis`: the 'hallucinated' fragalysis dataset that has been curated

## Status Options:
* `Planned`
* `Running`
* `Finished`
* `Packaged` (turned into a zip file ready to be handed off)
* `Delivered` (given to someone)
* `Blocked - {reason}`

**Comment by JenkeScheen** [comment]
great! Another status option could be `blocked` with a reason, e.g. a dependency. We could also consider .yaml instead of .csv, it seems to me most of this type of recording has been done this way in other repos in the lab?

**Comment by apayne97** [comment]
added! yaml could be good to, I was just thinking CSV might be nice for people further down in the pipeline so that they can look at it will excel or google sheets or something! Either way

**Comment by ijpulidos** [comment]
Yes, both options are good and we do need to think of who's going to be the potential user of this metadata and how would they access it. YAML is more human readable and doesn't require specific software to parse it, but is this what we expect from the users of this metadata? I don't know.

**Comment by apayne97** [comment]
started a version here: https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/data/datasets.yaml

**Comment by hmacdope** [comment]
Stale
