### ISSUE TITLE
End to end workflow is broken for proteins without a ligand. 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#453]
@ijpulidos tested the workflow for ligand-less proteins, finding that it failed in `split_openeye_mol`

We should fix this and also add a test for this code path so we don't break it again.

**Comment by kaminow** [comment]
just so I don't forget, I think we tracked down (one of) the bug to this code: https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-modeling/asapdiscovery/modeling/modeling.py#L766, with the issue being that if the design unit doesn't have a ligand, Python will throw a `StopIteration` exception

**Comment by hmacdope** [comment]
Fix is in #454
