### ISSUE TITLE
Create an API docs page somewhere

### ISSUE THREAD

**Issue by kaminow** [choderalab/asapdiscovery#458]
It would be super nice to have an API reference (like ReadTheDocs or something) now that we're building out the schematization and everything. Happy to help with this, although I don't have any experience working with these kinds of packages. Tagging @hmacdope @mikemhenry @ijpulidos because I feel like y'all might have done this at some point for other packages.

**Comment by mikemhenry** [comment]
This is a good question. Each package can have its own API documentation (from the doc strings) but we do need a central location for topics that span more than one package.
