### ISSUE TITLE
Intermittent failure on `test_fragalysisfactory_equal`

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#463]
`test_ff_equal` appears to be failing on and off. I will try and get to the bottom of it.

**Comment by kaminow** [comment]
I noticed this a bit as well, but I really have no idea what's happening. my only thought is that somehow the directories aren't in the same order between the two, but they're using the same CSV file and just iterating through the rows in order so idk how they could be different.

**Comment by JenkeScheen** [comment]
we should fix this soon so that we can work with CI again.

**Comment by kaminow** [comment]
I can try and look into it a bit

**Comment by hmacdope** [comment]
it may be to do with the ligand or target schema itself possibly.

**Comment by kaminow** [comment]
ok I think I figured it out. it looks like the inequality is coming from the second line in the ligand SDF files, which gives the date and time the molecules were created. ie this will occur when the molecule objects were created in different minutes... I'll make a quick change to `Ligand.__eq__` to account for this

**Comment by hmacdope** [comment]
Amazing work @kaminow thanks for investigating!
