### ISSUE TITLE
Use pathlib instead of strings for paths!

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#49]
At least we should replace hard coded stuff like this:
https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/scripts/hallucinate_fragalysis.py#L117
```
f"{in_dir}/{compound_id}/{dimer_s}/{best_str}"
```
with `os.path.join`.

But I guess using pathlib instead of using strings at all is even better.

**Comment by hmacdope** [comment]
Right idea, but this issue is too general.
