### ISSUE TITLE
on prep, align to a representative structure

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#524]
with `fragalysis` uploads broken, currently a large part of crystal structures that we're pulling in from a google drive folder (ugh) are not aligned to each other. This messes up a whole bunch of html and gif viz viewing angles. We should, for each target, pick a representative complex and when prepping a structure align to that reference.

**Comment by kaminow** [comment]
alignment to a reference structure is already built in to the protein prep pipeline I believe: https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-modeling/asapdiscovery/modeling/modeling.py#L45

**Comment by JenkeScheen** [comment]
perhaps we're just not calling it in end2end, @hmacdope ?
