### ISSUE TITLE
Add filtering step to `large-scale` docking 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#526]
Following discussion with @JenkeScheen we should formalise a configurable filtering process that selects good hits out of the results from a large scale docking run.

**Comment by kaminow** [comment]
would it make sense to have something similar to out `Selector` classes that would have a `select` method that takes in a `DockingResult` and returns a smaller `DockingResult`?

**Comment by hmacdope** [comment]
Done in #523
