### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#53]
They will go in `covid_moonshot_ml/tests/`
Currently we only have the very minimal https://github.com/choderalab/covid-moonshot-ml/blob/main/covid_moonshot_ml/tests/test_covid_moonshot_ml.py

**Comment by ijpulidos** [comment]
I think we are somewhat urgently needing this, especially with the new subpackage layouts. Each package will now have its own test directory. I'll try to make this a priority in my TODOs for this project.

**Comment by apayne97** [comment]
Now working towards this with 
- #182 
- #222 
- #223

**Comment by ijpulidos** [comment]
This can be closed now.
