### ISSUE TITLE
Add more dramatic stop if using version of mtenn incompatible with ML model

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#532]
We should throw some kind of exception rather than allowing continuation with rubbish numbers.

**Comment by hmacdope** [comment]
@kaminow something to investigate as part of improvements to ML package would be to add version pinning information to the ML model yaml file which can then be compared against introspection of MTENN version.

**Comment by hmacdope** [comment]
@kaminow I think we should get onto this one as we keep pushing out new mtenn releases and it is becoming hard to track which models work with which mtenn versions.

**Comment by kaminow** [comment]
yeah I think this sounds like a good idea. do you have any thoughts on how to proceed? my naive idea would be to add a fixed field to the `mtenn.Model` class that stores the version of `mtenn` that the model was built with, and then separately we'd maintain a compatibility table. not sure if this is the best way though or if there's a generally accepted way of doing this

**Comment by kaminow** [comment]
@hmacdope I've started working on this in the PR above. should be able to knock it out tomorrow morning but just wanted to get something up for now
