### ISSUE TITLE
need to add some new targets currently in P3

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#563]
we need to add:

- `DENV-2-NS2B-NS3`
- `EVD-68-3C`
- `EVA-71-3C`

we'll need to add them to the list of allowed targets, but also sprinkle them throughout the repo. We'll use this issue to canonicalize adding of new targets.

**Comment by hmacdope** [comment]
I think the required steps are:

1. Update `manifold_data_tags.yaml`
2. Put in a SEQRES as a yaml
3. Put in a master structure to align to.

**Comment by hmacdope** [comment]
We should also add some CI that checks that all the requisite things are present when a new host is defined, this shouldn't be too tricky.
