### ISSUE TITLE
host simple webpage that allows users to drop in PDB file and view fitness and canonical viz

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#566]
Given that we now have a way to generate the canonical viz for a PDB file (https://github.com/choderalab/asapdiscovery/pull/558), there might be an opportunity here to host a webpage that allows users to drop in their PDB complex, then select from a dropdown of allowed `TargetTag`s, and then displays the fitness and/or canonical viz as on an S3-hosted HTML file, or allow download of the `.pse`. 

_This would solve a great need within the consortium when it comes to viewing structures._ It would also allow folks to view fitness data with whatever compounds/fragments they have generated on-the-fly - this would unlock P1-3 fitness inspection without using any programming. These URLs would be hosted in the same way we do for our docking workflows: permanent URLs that can be passed around between folks.

In principle the code for generating the HTMLs and `.pse` is already here - we just need to host this online and build a basic web UI. We'll need to add more fitness data to `metadata` - I can take care of that. Perhaps there's a quick-and-dirty way of doing this on AWS as we're already hosting HTML files on S3?

**Comment by JenkeScheen** [comment]
the compute for this is very light CPU, only a fraction of a second. Would it make sense to run that on AWS?

**Comment by hmacdope** [comment]
We could probably run the compute directly on the AWS host or on Lambda if it needs a bit more juice. I will look into how we might serve the web UI and get back here with an answer.

**Comment by mikemhenry** [comment]
I think we can host this on AWS (or some other web server). I would use something like django so we have a batteries included platform to start with. Auth could be email/token based with an allowed list for domains (so for example, anyone with @choderalab.org email can login). A user can upload a PDB file + select the target and then they get re-directed to a different page that has the html file for their viz. We can setup the urls so that we cache the results so its like `example.com/md5hash(pdb_file+target_name/index.html` so if two users upload the same pdbfile + target selection, we don't have to re-make the html.

**Comment by JenkeScheen** [comment]
should we host the code on this repo (e.g. `asapdiscovery-web`) or somewhere secluded bc of security concerns?

**Comment by mikemhenry** [comment]
We can host the code anywhere, it can be public (no security issues with that). I think we should use a separate repository and we can import/install what we need from `asapdiscovery`. We can make a new repo called `asapdiscovery-web` under the choderalab org.

**Comment by hmacdope** [comment]
> We can host the code anywhere, it can be public (no security issues with that). I think we should use a separate repository and we can import/install what we need from `asapdiscovery`. We can make a new repo called `asapdiscovery-web` under the choderalab org. 

Sounds like a plan! Let's discuss this coming week?

**Comment by JenkeScheen** [comment]
closing as we're continuing discussions here: https://github.com/asapdiscovery/argos/issues/1
