### ISSUE TITLE
Make prepped structure caching more "cache" like

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#571]
Currently the way structure caching works is more like a dump than a cache, requiring all structures that need to be prepped be present in the cache.

Instead the cache should act as a an actual "cache ", ie searching for if the target has been prepped before by a name based match, and IF NOT prepping it and adding to the cache. 

One question here is how we avoid collisions, eg with structures that have unclear names, eg `protein.pdb`. We should probably also add some heuristics to avoid overwrrites and collisions.

**Comment by kaminow** [comment]
adding on to this, it seems like the `protein_prep_workflow` quietly deletes and replaces whatever `output_dir` you give it, which might be better to have as an option

**Comment by apayne97** [comment]
Also the current workflow waits until all the prepped complexes are made to save them - should be done in parallel otherwise if something bad happens you lose everything: https://github.com/choderalab/asapdiscovery/blob/0432f69fc99c85a923a498bf6ba6f117d3e703f3/asapdiscovery-modeling/asapdiscovery/modeling/workflows/protein_prep.py#L260-L271

**Comment by hmacdope** [comment]
I guess my idea was that saving to disk should be seperate of the computation, ie you can cache prepped complexes any time, not just when they are being prepped.

Would a partially complete "cache" not be misleading? You would then have to remember that it was only partially finished (and most probably remove it). This is also partially due to the limitations in current caching which treats a "cache" (inverted commas) as a fully complete dump of the prepped structures.

**Comment by hmacdope** [comment]
Fixed
