### ISSUE TITLE
Determine how schema / classes / functions / scripts / workflows / cli should be organized

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#587]
To me it doesn't feel like we're being consistent with where we put different parts of the code?

I think in general the kinds of code we have go from
Schema --> Classes / Functions that do the core functionality --> scripts to make it easier to use --> cli to use those scripts from the commandline

**Comment by hmacdope** [comment]
I agree with this as a general principle

> Schema --> Classes / Functions that do the core functionality --> scripts to make it easier to use --> cli to use those scripts

Would be helpful if you can point out where this isn't roughly being followed and we can evaluate if its not fitting pattern or why that is?

**Comment by hmacdope** [comment]
I think we have kind of sorted this out now? Re-open if not.
