### ISSUE TITLE
Fix not-equal bug in DataModelAbstractBase

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#619]
The not-equal method of DataModelAbstractBase should just be `not _eq__`, right? Otherwise if your class that subclasses it doesn't have a `data` method, it throws an error.

https://github.com/choderalab/asapdiscovery/blob/671776df4f1cbb8f24a200b175478f554e26299d/asapdiscovery-data/asapdiscovery/data/schema_v2/schema_base.py#L79-L89

**Comment by hmacdope** [comment]
Yep I think you are right, should share implementation.
