### ISSUE TITLE
Make project pyproject.toml installable from root

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#625]
Currently you cannot install all the subpackages from the top level, meaning a conda install with 

`git+https://github.com/choderalab/asapdiscovery@main` will fail. This is annoying for packages that depend on asapdiscovery eg `argos`

From reading the docs, this seems like it should be fixable. @mikemhenry do you have any experience with this kinda thing? Ill have a stab but seems like it will be a bit of trial and error.

**Comment by mikemhenry** [comment]
This should JustWork :tm: 

`pip install --no-deps "git+https://github.com/choderalab/asapdiscovery#egg=asapdiscovery-cli&subdirectory=asapdiscovery-cli"`

**Comment by hmacdope** [comment]
Incredible!
