### ISSUE TITLE
[upstream] coming changes to postera bleaching of column names 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#628]
Postera have indicated that they are removing bleaching of dashes to underscores for column names on the manifold backend. 

Currently our  columns like "a-b_c" are being database encoded as "a_b_c". 

This means that once this upstream change is made and we continue to upload project support tickets, we will end up with duplicate column names where some have the old signature and some have the new signature. There is also the potential for some molecule sets to have both if they are re-used for project support tickets.

 While the second state without bleaching is the preferable end result, how do we want to deal with old molecule sets?

1. Do nothing, but DB/UI will be a bit messy, potential for confusion. This is mainly dependent on how useful old molecule sets are to medchemists. 
2. Do a migration (scary) on our end (in tandem with postera).
3. Postera can possibly do a migration?
4. Something else.

Tagging @JenkeScheen and also @dotsdl in a technical advisory role.

**Comment by JenkeScheen** [comment]
what are the risks of `2`?

**Comment by hmacdope** [comment]
> what are the risks of `2`?

We could stuff up all the molecule sets irreparably if we do it wrong.

**Comment by hmacdope** [comment]
Resolved,  assuming no migration.
