### ISSUE TITLE
Docking CI needs to be cut down. 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#668]
Currently it is taking over an hour, we need to remove some tests from docking CI so that it can run in a more reasonable timeframe. 

Once we start to cut on a 0.2.0 this will burden will be reduced.

**Comment by apayne97** [comment]
would it be possible to have nightly tests instead of CI for some of these things?

**Comment by hmacdope** [comment]
Yes, need to add a nightly flag as an environment variable I think is best way.

**Comment by hmacdope** [comment]
As a start here, lets cut enumeration of a bunch of option in old workflows.
