### ISSUE TITLE
Github actions Workflow creating container/apptainer

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/asapdiscovery#699]
We have noticed that it is getting harder to create reproducible environments for the tools and packages in this repository. It would be of great help to have a workflow that generates docker containers or singularity apptainers and publish them. Especially for our users and researchers to run on infrastructure like HPC system (lilac) or similar.

We have experimented with something similar in [perses](https://github.com/choderalab/perses/actions/workflows/docker.yaml) (even though we probably have to run that one manually, but it shouldn't be that hard to automate it, if we need to)

**Comment by hmacdope** [comment]
Sounds good. This could be paired well with integration tests run on said container.

**Comment by hmacdope** [comment]
@ijpulidos would you like to tackle this one or would you like me to? Using the approach from [OpenFe](https://github.com/OpenFreeEnergy/openfe/blob/main/production/Dockerfile) or [argos](https://github.com/asapdiscovery/argos/blob/main/Dockerfile) (the two are similar, using the mamba base image) would be a good place to start.
