### ISSUE TITLE
ASAP-Alchemy: `status` on of scope

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#712]
when we've submitted multiple networks, we can enter each production folder and call `asap-alchemy status`. It would be useful to be able to query all asap-related data in `status`, by e.g. `asap-alchemy status --all` which would print out the usual table but instead shows all running/queued/finished (etc) tasks on `alchemiscale`. I believe this is already possible with the `alchemiscale` API.

**Comment by JenkeScheen** [comment]
use-case: I currently have 11 networks submitted, it's cumbersome to have to go to each of these folders to see if they've all finished. 

Bonus: if `alchemiscale` ends up returning *all* finished tasks, we can nicely keep track of how much we've run with ASAP!

**Comment by JenkeScheen** [comment]
it could be a `asap-alchemy status --all` call, that first prints the table you just showed, then starts to go over all networks that currently have tasks `running` or `waiting`?

**Comment by hmacdope** [comment]
I think this was fixed @jthorton

**Comment by JenkeScheen** [comment]
yup!
