### ISSUE TITLE
ASAP-Alchemy: guardrail/ enforce setting of ligand names

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#727]
currently if no ligand names are set in the SDF inputs for `asap-alchemy submit`, this network is submitted to `alchemiscale` and after simulations and `asap-alchemy gather`, gathered edges have empty strings as names which means we can't predict on them anymore: 
```
{
        "type": "TransformationResult",
        "ligand_a": "",
        "ligand_b": "",
        "phase": "solvent",
        "estimate": {
          "magnitude": -14.6842962125111,
          "unit": "kilocalorie / mole",
          ":is_custom:": true,
          "pint_unit_registry": "openff_units"
        },
        "uncertainty": {
          "magnitude": 0.08448160502963074,
          "unit": "kilocalorie / mole",
          ":is_custom:": true,
          "pint_unit_registry": "openff_units"
        }
      }, 
```
Instead, we should be enforcing the naming of ligands before they are sent off to `alchemiscale`, or at least add a guardrail that applies some kind of ligand name (e.g. by `gufe` key).

**Comment by dotsdl** [comment]
Working on this; thanks @JenkeScheen!
