### ISSUE TITLE
Remove unused components following refactor.

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#735]
Many components and files have become unused in the latest generation of workflows. 
We should remove these files as part of our cleanup efforts.

**Comment by apayne97** [comment]
@hmacdope does it make sense to make a new GitHub "project" for the removal process? I'm not sure how much it matters but I guess the building up and the breaking down are kinda different steps

**Comment by hmacdope** [comment]
Doing in 3 steps,

* remove unused
* Migrate some things
* finish transition to V2
