### ISSUE TITLE
Building the environment via the yaml files grabs the CPU version of pytorch

### ISSUE THREAD

**Issue by kaminow** [choderalab/asapdiscovery#743]
As the title says, when trying to build the `asapdiscovery` environment via `mamba env create -f devtools/conda-envs/asapdiscovery-ubuntu-latest.yml`, the solver tries to install the CPU-only build of `pytorch`. It does also install `cudatoolkit`, but for some reason that's not making it across to `pytorch`.

**Comment by hmacdope** [comment]
Does installing `pytorch-gpu` as a conda-package work?

**Comment by hmacdope** [comment]
I think #744 fixed this.
