### ISSUE TITLE
Add handling of extra_config option in Trainer

### ISSUE THREAD

**Issue by kaminow** [choderalab/asapdiscovery#753]
I think I forgot to add this when I was implementing the `Trainer` class, but  there is currently no parsing the <key>,<value> pair strings being passed to `extra_configs`. Should be a quick fix of just adding a `validator` for that `Field`.

**Comment by hmacdope** [comment]
@kaminow did we end up fixing this?

**Comment by kaminow** [comment]
ah no I haven't yet. thanks for the reminder, I'll bump it up on my list
