### ISSUE TITLE
Alchemy: need to monitor a network's actioned tasks

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#869]
I recently (somehow) had a network with hundreds of tasks un-actioned and didn't realize for ~ a week. The task breakdown for networks with `status -a` doesn't show this:
![image](https://github.com/choderalab/asapdiscovery/assets/43140137/3afe3ca3-1dde-483e-9afa-07828a41bbab)
which made me think I just had no compute available for that time. 

I'm wondering what the cleanest way of showing this is.. Perhaps a column for `actioned` and one for `not actioned`? But that doesn't reflect that it's `n tasks` very well. Perhaps we could play with [multi-level headers](https://stackoverflow.com/questions/74144874/constructing-a-table-with-multilevel-headers-using-rich-table) where the top one says `n tasks`, and bottom ones are `actioned` and `not actioned`.

**Comment by jthorton** [comment]
Added in #846
