### ISSUE TITLE
Find more permanent solution to memory hungry ML CLI testing

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#874]
@fyng @kaminow, the CLI training tests are chewing up 50 Gb+ memory, I have added a swapfile in the runner but we should possible try and use mocking instead to avoid the expensive calls.

_Originally posted by @hmacdope in https://github.com/choderalab/asapdiscovery/issues/789#issuecomment-1960653713_

**Comment by hmacdope** [comment]
The best way is probably to mock the training call by loading in some weights from file or something.

**Comment by kaminow** [comment]
another solution to this I think will just be using smaller models (ie just decreasing the hyperparameters on the CLI). if one of you has time to take a stab that would be great otherwise I can take care of it in the next couple days

**Comment by hmacdope** [comment]
@kaminow I think we can consider this fixed?
