### ISSUE TITLE
Add genetics subpackage 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#890]
We need a new subpackage for the work @mariacm12 is doing, and also as a home to collect some of the fitness stuff under one umbrella. Related to #769

**Comment by hmacdope** [comment]
Name is up for debate, did we come up with anything better @apayne97 @kaminow ?

**Comment by JenkeScheen** [comment]
I think it's OK for now, it's general enough to encompass a bunch of stuff.
