### ISSUE TITLE
MAFFT depedency for new `genetics` work, need conda-forge

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#893]
@mariacm12 has been working on some sequence alignment tooling, this may depend on the MAFFT package. https://mafft.cbrc.jp/alignment/software/

It is available on the old deprecated bioconda channel, we should think about putting it on conda-forge.

**Comment by hmacdope** [comment]
We can probably just steal the recipie directly: 

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mafft/meta.yaml

**Comment by hmacdope** [comment]
Recipe pending approval : https://github.com/conda-forge/staged-recipes/pull/25606

**Comment by bgruening** [comment]
Why is the bioconda channel deprecated?

**Comment by hmacdope** [comment]
@bgruening we want to have this package be all conda-forge installable, so that this package can be deployed with conda-forge itself.

I suppose in this case it isn't strictly necessary as we don't import or link to MAFFT, but the idea remains that you  should be able to install deps for a conda-forge package strictly from the conda-forge channel.

**Comment by bgruening** [comment]
I was referring to

> It is available on the old deprecated bioconda channel, we should think about putting it on conda-forge.

This is not clear to me and I still don't see a technical reason. The recipe is maintained as you can see.

> idea remains that you should be able to install deps for a conda-forge package strictly from the conda-forge channel

I get that, but as a consequence, if we follow this logic, this means that we need to move all recipes over to conda-forge - which might be a hard sell.

**Comment by hmacdope** [comment]
@mariacm12  MAFFT is now available on conda-forge :)
