### ISSUE TITLE
`alchemy`: set correct order of CLI endpoints on top-level `--help`

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#896]
As per title, we should correctly order the output to follow (roughly) the order that a user would execute them in:
```
$ asap-alchemy --help
Usage: asap-alchemy [OPTIONS] COMMAND [ARGS]...

  Tools to create and execute Alchemy networks using OpenFE and alchemiscale.

Options:
  --help  Show this message and exit.

Commands:
  create   Create a new free energy perturbation factory with default...
  gather   Gather the results from alchemiscale for the given network.
  plan     Plan a FreeEnergyCalculationNetwork using the given factory...
  predict  Predict relative and absolute free energies for the set of...
  prep     Tools to prepare ligands for Alchemy networks via state...
  restart  Restart errored Tasks for the given FEC network.
  status   Get the status of the submitted network on alchemiscale.
  stop     Stop (i.e.
  submit   Submit a local FreeEnergyCalculationNetwork to alchemiscale...
```

which is `create`, `prep`, `plan`, `submit`, `status`, `stop`, `gather`, `predict`.

At the same time we can also fix `stop` which seems to be formatted wrong, looks like it's being cut short.

**Comment by jthorton** [comment]
These are currently put into alphabetical ordering by click, its simple enough to change the ordering to follow the order they are defined in. If we do this automatically I don't think we can have `prep` be listed second as its a sub command, to do this we would have to define the ordering manually and update this every time we add a new cli command. 

We would need to add a custom group class and define how the commands should be listed to have defined order.
```python
import click

class OrderedGroup(click.Group):
    def list_commands(self, context):
        self.commands.keys()

# use to define the group
@click.group(cls=OrderedGroup)
def alchemy():
    pass
```

**Comment by hmacdope** [comment]
Fixed by @JenkeScheen
