### ISSUE TITLE
`alchemy`: automatically add refernce compounds to a network

### ISSUE THREAD

**Issue by jthorton** [choderalab/asapdiscovery#897]
To improve the accuracy of our free energy predictions we should be adding reference compounds to our planned networks which have assay data in CDD. 

MVP:
The plan is to extend the `prep` stage to accept a CDD protocol name and the number of compounds which we should try and add. Then after sorting by similarity to the crystal reference compound we should try and generate a pose for each molecule until either we hit the requested number or run out of molecules. These compounds will then be tagged as experimental reference compounds. 

Stretch:
Penalise the network planner to not add connections between the experimental compounds, this should mean that the compounds are distributed through the network and then during the predict stage we can add extra edges with the experimentally determined differences which should help improve the accuracy of the network.

cc: @JenkeScheen

**Comment by JenkeScheen** [comment]
for the Stretch goal, we might also want to consider finding compounds in CDD _that are similar to non-reference ligands in the series_, which could potentially increase the chances of finding enough similar experimental compounds to inject.

**Comment by hmacdope** [comment]
@jthorton @JenkeScheen can you link the relevant PR that closes this to this issue. I am not sure which one of #919 or #938 fixes this.
