### ISSUE TITLE
Ligand schema | make `data` a computed property?

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#903]
Since we've storing the interesting bits in the 'tags' and we actually use `to_oemol` to write out the molecule, the `.data` property doesn't actually represent the internal data state.

Instead I think we should make `.data` this:

```
@property
def data(self) --> str:
    mol = self.to_oemol()
    return oemol_to_sdf_string(mol)
```

**Comment by jthorton** [comment]
We do have this currently but we call it [to_sdf_str](https://github.com/choderalab/asapdiscovery/blob/cf611d1ab9e9f44255c99df91992aa550ed35a95/asapdiscovery-data/asapdiscovery/data/schema/ligand.py#L393) but we could change the name, but we still need to store the raw sdf string somewhere which we use for conversions. Are you saying we should change its name from data to be clear it is just a raw sdf?

**Comment by hmacdope** [comment]
As @jthorton says `.data` has to hold the internal state, if we eliminate `.data` then `self.to_oemol()` has nothing to pull from.

**Comment by hmacdope** [comment]
I am going to close here @apayne97? Re open if want to continue discussion
