### ISSUE TITLE
Rename repository to `asapdiscovery`; make namespace package

### ISSUE THREAD

**Issue by dotsdl** [choderalab/asapdiscovery#97]
Following on from [this proposal](https://github.com/choderalab/covid-moonshot-ml/issues/23#issuecomment-1301650382), we should rename this repository to `asapdiscovery` and make the Python package [a namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/).

This will make the `asapdiscovery` top-level module name a namespace only, with `import asapdiscovery` doing nothing. It will allow for e.g. `import asapdiscovery.data as aspdata` to just work, while also allowing us to create other modules in the `asapdiscovery` namespace in perhaps other repos in the future.

**Comment by apayne97** [comment]
@dotsdl @mikemhenry @ijpulidos what is needed for this to happen? is this a PR thing or just a "change the name of the repo on github" thing?

**Comment by dotsdl** [comment]
We don't need to do the pkgutil-style approach; we should be able to use the "native" approach (also known as *implicit*): https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages

I'll put together a PR implementing this.
